name: Hairy Violet Herbal
author: Heather Davidson
url: https://hairy-violet-herbal.netlify.app
logo: /static/images/t.png
thumbnail: /static/images/default_thumbnail.jpg
socials:
  instagram: https://www.instagram.com/hairyvioletherbal/
